### PR TITLE
Translate Chapter 5 and modify the source file format

### PR DESCRIPTION
**Pull request by Jzow**
### Description

<Please describe the issues fixed by this PR>

Related Issue: CC https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/issues/166

### Pre-commit steps

 - [ ] Tested on QEMU and real HW Rasperry Pi.
     - Not needed if it is just a README change or similar.
 - [x] Ran `./contributor_setup.sh` followed by `./devtool ready_for_publish`
     - You'll need `Ruby` with `Bundler` and `NPM` installed locally.
     - If no Rust-related files were changed, `./devtool ready_for_publish_no_rust` can be used instead (faster).
     - This step is optional, but much appreciated if done.

### CODE REVIEW

**Comment by Jzow** [comment]
CC @colachg @readlnh  Please review, thanks.

**Comment by Jzow** [comment]
@posborne Please review, thanks.

**Comment by Jzow** [comment]
@eldruin Hi friend, I noticed that three friends who maintain Chinese translations have not been active on Github for a long time, and the PR for this translation may not receive feedback. Therefore, I suggest finding a partner to proofread translation files. I want to complete this work earlier.

**Comment by eldruin** [comment]
Hi @Jzow, I have asked in our [chat room](https://matrix.to/#/#rust-embedded:matrix.org) but nobody responded.
Do you feel confident enough with your translation so that we could merge it as-is (after rebasing to master so that CI works)?
Users can always submit improvements/fixes later on.

**Comment by Jzow** [comment]
> I have asked in our [chat room](https://matrix.to/#/#rust-embedded:matrix.org) but nobody responded.

Thanks for your prompt reply.

> Do you feel confident enough with your translation so that we could merge it as-is (after rebasing to master so that CI works)?

Firstly, I am happy to do translation work, making it easier for some friends to read. At the same time, I can also understand embedded knowledge from it so that I can try to contribute code from `rust-embedded` repositories in the future. I believe I should be competent for this translation job. **If there are any translation issues, I will proofread and update them at any time.**

If there are new colleagues to submit improvements/fixes in the future, that would be great.

**Comment by eldruin** [comment]
Ok, thanks. Once you rebase this to master so that CI works, I will merge it.

**Comment by Jzow** [comment]
Don't need to change to the master branch, just reopen it and have it perform CI validation once.

Each chapter translation should correspond to a branch, and after merging, I will delete the corresponding branch of my fork.

**Review by eldruin — APPROVED** [review]
Thank you!

**Pull request merged**
