### PR TITLE
Added short explanation for the BRD calculations ref #70

### PR DESCRIPTION
**Pull request by cfsamson**
I tried to keep the comment short but still show the calculations so it's easier to understand where the numbers come from. Let me know if you want anything changed.

### CODE REVIEW

**Comment by andre-richter** [comment]
Thanks, that's perfect.

Can you add it to the `X1_JTAG_boot` folder as well please (I always forget that folder myself...)?

Also, I need to check why the Sanity Checks CI fails, stay tuned.

**Comment by cfsamson** [comment]
Oh, I missed that. Added it to `X1_JTAG_boot` now. 

I saw the check failed but I have no idea what's causing it. I can't see anything wrong. Unfortunately, installing the dev tools on my machine leads me to [this lovely issue](https://github.com/hparra/ruby-serialport/issues/53) in ruby-serialport (probably some build dependency in Ruby I need to install), so there is no quick way for me to run this locally right now. Let me know if you figure out what's failing.

**Comment by cfsamson** [comment]
OK, so I got the devtools working and I fixed the issue. Github seems to have som problems right now so so it doesn't update the PR but I'll check back in some time and check if it's updated.

**Comment by cfsamson** [comment]
Everything looks good now!

**Comment by andre-richter** [comment]
Awesome. What was the issue?

**Comment by cfsamson** [comment]
I'm not sure. I resolved it by deleting the existing comment and copying the comment segment from chapter 10. My guess is that I either accidentally inserted a non-breaking space (the typical shift+space "space"), a hard tab instead of 4 spaces or something like that.

The latter is probable since I had to switch to tabs in my editor when porting the makefile to [cargo make](https://crates.io/crates/cargo-make).

**Pull request merged**
