### PR TITLE
01_wait_forever: support riscv32/riscv64

### PR DESCRIPTION
**Pull request by imsut**
Add support for riscv32/[HiFive1](https://www.sifive.com/boards/hifive1) and riscv64/[HiFive Unleashed](https://www.sifive.com/boards/hifive-unleashed) in section `01_wait_forever`.

When I was testing riscv32 with QEMU, I encountered a problem, probably the same issue as [this](https://github.com/riscv/riscv-qemu/issues/137).
Although I do not own "HiFive Unleashed" board, adding riscv64 helps me develop as the issue does not happen with `sifive_u` machine on QEMU.

```
❯ make qemu BSP=hifive1
RUSTFLAGS="-C link-arg=-Tsrc/bsp/hifive1/link.ld -C target-cpu=generic-rv32 -D warnings -D missing_docs" cargo rustc --target=riscv32imac-unknown-none-elf --features bsp_hifive1 --release
   Compiling kernel v0.1.0 (/home/kenkawamoto/personal/rust-raspberrypi-OS-tutorials/01_wait_forever)
    Finished release [optimized] target(s) in 0.19s
----------------
IN:
Priv: 3; Virt: 0
0x00001000:  204002b7          lui             t0,541065216
0x00001004:  00028067          jr              t0

----------------
IN:
Priv: 3; Virt: 0
0x20400000:  10500073          wfi
0x20400004:  bff5              j               -4              # 0x20400000
```

```
❯ make qemu BSP=hifive_unleashed
RUSTFLAGS="-C link-arg=-Tsrc/bsp/hifive_unleashed/link.ld -C target-cpu=generic-rv64 -D warnings -D missing_docs" cargo rustc --target=riscv64gc-unknown-none-elf --features bsp_hifive_unleashed --release
    Finished release [optimized] target(s) in 0.06s
----------------
IN:
Priv: 3; Virt: 0
0x0000000000001000:  00000297          auipc           t0,0            # 0x1000
0x0000000000001004:  02028593          addi            a1,t0,32
0x0000000000001008:  f1402573          csrrs           a0,mhartid,zero

----------------
IN:
Priv: 3; Virt: 0
0x0000000000001000:  00000297          auipc           t0,0            # 0x1000
0x0000000000001004:  02028593          addi            a1,t0,32
0x0000000000001008:  f1402573          csrrs           a0,mhartid,zero

----------------
IN:
Priv: 3; Virt: 0
0x000000000000100c:  0182b283          ld              t0,24(t0)
0x0000000000001010:  00028067          jr              t0

----------------
IN:
Priv: 3; Virt: 0
0x000000000000100c:  0182b283          ld              t0,24(t0)
0x0000000000001010:  00028067          jr              t0

----------------
IN:
Priv: 3; Virt: 0
0x0000000080000000:  10500073          wfi
0x0000000080000004:  bff5              j               -4              # 0x80000000

----------------
IN:
Priv: 3; Virt: 0
0x0000000080000000:  10500073          wfi
0x0000000080000004:  bff5              j               -4              # 0x80000000
```

### CODE REVIEW

**Comment by andre-richter** [comment]
That’s an exciting PR, thanks!

I have only mobile internet access until next week, will review asap then!

**Comment by imsut** [comment]
> I have only mobile internet access until next week, will review asap then!

no probs @andre-richter ! 
if you have time next week to review the change, that would be great.

**Comment by andre-richter** [comment]
Hi,

I just had a first glance at your PR. I see that you added the HiFive1. It is an Arduino class board with a CPU that does not have an MMU, and is therefore not suited for these tutorials.
The Unleashed, on the other hand, makes sense.

I'll spend some time to get it running locally and come back here with my findings.
You can remove the HiFive1 in the meantime if you like.

Best,
Andre

**Comment by imsut** [comment]
ahh, I should have checked if HiFive1 has MMU. my bad.
Unfortunately, I do not have HiFive Unleashed (and it's not sold today).  I'll drop this PR.  I will try again if I somehow get the Unleashed board.

Thanks for taking the time to review, Andre!

**Comment by andre-richter** [comment]
lea_is_here <notifications@github.com> wrote:
“

ahh, I should have checked if HiFive1 has MMU. my bad.

Unfortunately, I do not have HiFive Unleashed (and it's not sold today).  I'll drop this PR.  I will try again if I somehow get the Unleashed board.

Thanks for taking the time to review, Andre!

**Pull request closed without merging**
