### PR TITLE
fix ci/cd error

### PR DESCRIPTION
**Pull request by Jzow**
### Description

<Please describe the issues fixed by this PR>

Related Issue: CC #184 

### Pre-commit steps

 - [x] Tested on QEMU and real HW Rasperry Pi.
     - Not needed if it is just a README change or similar.
 - [x] Ran `./contributor_setup.sh` followed by `./devtool ready_for_publish`
     - You'll need `Ruby` with `Bundler` and `NPM` installed locally.
     - If no Rust-related files were changed, `./devtool ready_for_publish_no_rust` can be used instead (faster).
     - This step is optional, but much appreciated if done.

### What did this PR do

1. Main reason: Because every time a PR is submitted during the translation of a chapter, a **Github CI** check will be conducted and an error will be reported.
2. Solution: Fix **Github CI** running errors.

### The following things were done to fix this error:

1. Modified the year check error, many files have a deadline of 2022, which can cause **Github CI** to make errors when running `bundle exec ruby utils/devtool.rb copyright`.
2. Modified the `settings.json` file and add `prettierrc. json`. If the code format is not followed, it will cause **Github CI** to run error when running `bundle exec ruby utils/devtool.rb fmt_check`.
3. Revised Ruby code format (method comments) to include `i.to_s ->i` It does not need to be called explicitly, which will cause **Github CI** to error when running `bundle exec ruby utils/devtool.rb rubocop`

Because I need to check many files, I cannot manually modify them one by one. I will replace them in bulk and finally convert the code format.

CC @eldruin @andre-richter

### CODE REVIEW

**Review by eldruin — COMMENTED** [review]
Thanks! it seems there is still a file missing, though, according to the CI.

**Comment by Jzow** [comment]
What did this PR do

1. Main reason: Because every time a PR is submitted during the translation of a chapter, a **Github CI** check will be conducted and an error will be reported.
2. Solution: Fix **Github CI** running errors.


The following things were done to fix this error:

1. Modified the year check error, many files have a deadline of 2022, which can cause **Github CI** to make errors when running `bundle exec ruby utils/devtool.rb copyright`.
2. Modified the `settings.json` file and add `prettierrc. json`. If the code format is not followed, it will cause **Github CI** to run error when running `bundle exec ruby utils/devtool.rb fmt_check`.
3. Revised Ruby code format (method comments) to include i.to_ S ->i It does not need to be called explicitly, which will cause **Github CI** to error when running `bundle exec ruby utils/devtool.rb rubocop`

Because I need to check many files, I cannot manually modify them one by one. I will replace them in bulk and finally convert the code format.

CC @eldruin @andre-richter

**Review by eldruin — COMMENTED** [review]
Thank you! Seems like a lot of work.
Are these changes in the comments necessary `##-------` -> `## ------` (notice the extra whitespace after `##`)?
Without those there would be many fewer changes in this PR.

**Comment by Jzow** [comment]
If there are no spaces after the # sign, it will also report code formatting errors

```

utils/devtool.rb:332:1: C: [Correctable] Layout/LeadingCommentSpace: Missing space after #.
##--------------------------------------------------------------------------------------------------
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
utils/devtool.rb:334:1: C: [Correctable] Layout/LeadingCommentSpace: Missing space after #.
##--------------------------------------------------------------------------------------------------
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

101 files inspected, 70 offenses detected, 70 offenses autocorrectable
Error: Process completed with exit code 1.

```

[error log](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/actions/runs/6167534955/job/16738641202)

**Comment by eldruin** [comment]
I see. Thanks for the clarification.
However, that should only be changed in the ruby files and should be unnecessary in the Makefiles, which make up a big portion of the changes, right?
Would it be possible for you to revert to `##-------` in the Makefiles?

**Comment by Jzow** [comment]
> I see. Thanks for the clarification. However, that should only be changed in the ruby files and should be unnecessary in the Makefiles, which make up a big portion of the changes, right? Would it be possible for you to revert to `##-------` in the Makefiles?

Yes, it seems that Ruby has a requirement for whitespace.

**Comment by eldruin** [comment]
Thanks! That has worked but I still see a lot of `## ----` in the makefiles. For example on line 91 and 93 of `01_wait_forever/Makefile`.
Maybe the search and replace did not work adequately due to a varying number of `-` being present.
Could you have another look?

**Comment by Jzow** [comment]
> Could you have another look?

Right, It seems much less now, just adding spaces to the Ruby files.

**Review by eldruin — APPROVED** [review]
Looks good to me, thank you for your work!

**Pull request merged**
