### PR TITLE
Change baud 576000 to 460800

### LINKED ISSUE #95: Unexpected Error: #<Errno::EINVAL: Invalid argument - tcsetattr>
I have a problem when trying 06_drivers_gpio_uart.
I got following error.

```
$ DEV_SERIAL=/dev/tty.usbserial-1420 make miniterm

Miniterm 1.0


[MT] ⚡ Unexpected Error: #<Errno::EINVAL: Invalid argument - tcsetattr>

[MT] Bye 👋
```

I think the cause of the error is `baud`.
The baud is depending on the platform according to the documentation.
I'm using Mac OS.

> Integer from 50 to 256000, depending on platform)
> https://rubydoc.info/gems/serialport/SerialPort:set_modem_params

The current value is `576000`

https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/blob/ff382c3fafa6257e37c208015cbea3aa3d1b2515/utils/miniterm.rb#L44

## Reproduce process

1. Use Mac OS.
1. Compile source.
1. Write binary to SD card.
1. Power on.
1. Run miniterm.

### PR DESCRIPTION
**Pull request by sachaos**
Fix #95 

macOS is not supporting baud `576000`.
To fix this problem use `460800` as baud.

### CODE REVIEW

**Comment by andre-richter** [comment]
Thanks, I will review later today. 

But you still need the stty command, right?

**Comment by sachaos** [comment]
@andre-richter 
> But you still need the stty command, right?

No. There is no need to run stty command.
I confirmed `SerialPort.new` accepted 460800 correctly.

**Comment by andre-richter** [comment]
> @andre-richter
> 
> > But you still need the stty command, right?
> 
> No. There is no need to run stty command.
> I confirmed `SerialPort.new` accepted 460800 correctly.

Even better!
The reason I bumped it recently is that upcoming tutorials might increase the kernel size quite a bit, so this is done in preparation to keep chainloading duration down.

Once I find time to review this, I might check if 921600 baud can also work on both macOS and Linux.

**Comment by andre-richter** [comment]
Hi @sachaos,

I am still in the process of testing `921600` baud. So far, it looks good on both Linux PC and Mac. Please bear with me until I am done. Thanks :+1:

**Comment by sachaos** [comment]
This PR is no longer needed.
Ref: #97

**Pull request closed without merging**
