### PR TITLE
Translation Chapter 4

### PR DESCRIPTION
**Pull request by Jzow**
### Description

<Please describe the issues fixed by this PR>

Related Issue: <Insert link here if applicable>

### Pre-commit steps

 - [ ] Tested on QEMU and real HW Rasperry Pi.
     - Not needed if it is just a README change or similar.
 - [x] Ran `./contributor_setup.sh` followed by `./devtool ready_for_publish`
     - You'll need `Ruby` with `Bundler` and `NPM` installed locally.
     - If no Rust-related files were changed, `./devtool ready_for_publish_no_rust` can be used instead (faster).
     - This step is optional, but much appreciated if done.

link https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/issues/166

### CODE REVIEW

**Comment by Jzow** [comment]
link #166

**Comment by Jzow** [comment]
@colachg Please review, thanks

**Comment by Phantato** [comment]
since it's about translation, I think commenting in Chinese is OK?

**Comment by Jzow** [comment]
> since it's about translation, I think commenting in Chinese is OK?

当然可以

**Comment by Jzow** [comment]
你可以check一下，如果没有问题，我们就需要进行合并。

**Review by Phantato — APPROVED** [review]
lgtm

**Comment by Jzow** [comment]
如果你有时间可以尝试翻译第五章，我继续第六章。

**Comment by eldruin** [comment]
@Jzow Please let us know when this is ready for merge

**Comment by Jzow** [comment]
> @Jzow Please let us know when this is ready for merge

This PR can be merged

**Pull request merged**
